// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Nav: typeof import('./src/components/Nav.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
  }
}

export { }
